version: "3.9"
 
services:
  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - ./mssql-server-data:/var/opt/mssql/data
      - ./mssql-server-logs:/var/opt/mssql/log
    environment:
      - ACCEPT_EULA=Y 
      - SA_PASSWORD=zaqWE*123
      - MSSQL_AGENT_ENABLED=True
      - MSSQL_PID=Developer
    ports:
      - 15789:1433
    container_name: ms-sqlserver2022
    restart: always
